# Generated by Django 2.0.2 on 2018-02-21 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MebliShop', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='image',
        ),
        migrations.AddField(
            model_name='product',
            name='additional_image',
            field=models.ImageField(blank=True, upload_to='products/<django.db.models.fields.CharField>_1/%Y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='product',
            name='additional_image_2',
            field=models.ImageField(blank=True, upload_to='products/<django.db.models.fields.CharField>_2/%Y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='product',
            name='additional_image_3',
            field=models.ImageField(blank=True, upload_to='products/<django.db.models.fields.CharField>_3/%Y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='product',
            name='main_image',
            field=models.ImageField(blank=True, upload_to='products/main/<django.db.models.fields.CharField>/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='depth',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='product',
            name='height',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='product',
            name='width',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
