# Generated by Django 2.0.2 on 2018-02-21 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MebliShop', '0002_auto_20180221_0728'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='additional_image',
            field=models.ImageField(blank=True, upload_to='products/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='additional_image_2',
            field=models.ImageField(blank=True, upload_to='products/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='additional_image_3',
            field=models.ImageField(blank=True, upload_to='products/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='main_image',
            field=models.ImageField(blank=True, upload_to='products/main/%Y/%m/%d/'),
        ),
    ]
