# Generated by Django 2.0.2 on 2018-02-21 07:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MebliShop', '0003_auto_20180221_0730'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='main_image',
            new_name='image',
        ),
    ]
