# Generated by Django 2.0.2 on 2018-03-01 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MebliShop', '0004_auto_20180221_0732'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('adress', models.CharField(max_length=200)),
                ('work_time', models.CharField(max_length=200)),
                ('life_tel', models.CharField(blank=True, max_length=20)),
                ('mts_tel', models.CharField(blank=True, max_length=20)),
                ('kievstar_tel', models.CharField(blank=True, max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='product_full_description',
            field=models.CharField(blank=True, max_length=1000),
        ),
    ]
