# Generated by Django 2.0.2 on 2018-03-25 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MebliShop', '0006_delete_shop'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_description',
            field=models.TextField(max_length=500),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_full_description',
            field=models.TextField(blank=True, max_length=2000),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_name',
            field=models.CharField(max_length=100),
        ),
    ]
